"""ALGUNAS VERSIONES GENERA ERROR O ALERTAS, PARA VERSION DE PYTHON 3.10.7
EL CORRECTO FUNCIONAMIENTO TIENE QUE SER EL SIGUIENTE"""
import cv2

# ASIGNACION DE IMAGEN A UNA VARIABLE
VarImageTest=cv2.imread('contorno.jpg')

# METODO DE VISUALIZACION DE INFORMACION
cv2.imshow('ViewImage',VarImageTest)

# INDICA QUE NO CIERRE LA VENTANA
# EL VALOR DE 0:[PARA IMAGEN ESTATICAS] O 1:[PARA IMAGEN FLUIDO]
cv2.waitKey(0)

# METODO DE VISUALIZACION DE VENTANA
cv2.destroyAllWindows()