import cv2
import  pip

"""
SE DEBE INSTALAR LAS ULTIMAS VERSIONES DE LOS SIGUIENTES
ULTIMA VERSION DE PYTHON
ULTIMA VERSION DE PIP
ULTIMA VERSION DE OPENCV
"""

print("\nVERSION DE OPENCV")
print(cv2.__version__)

print("\nVERSION DE PIP")
print(pip.__version__)

